# Generated by nixgen — do not edit by hand.
# channel: nixos-26.05   generated: 2026-08-11 11:31   nixgen: 2026-08-12f
#
# Import it:  imports = [ ./generated.nix ];
# Or use it in place of your configuration.nix.
# Either way keep it beside ./hardware-configuration.nix.

{ config, lib, pkgs, ... }:

{
  console.keyMap = "jp106";
  environment.sessionVariables.XKB_DEFAULT_LAYOUT = "jp";
  i18n.defaultLocale = "ja_JP.UTF-8";
  i18n.inputMethod.enable = true;
  i18n.inputMethod.fcitx5.addons = [ pkgs.fcitx5-mozc ];
  i18n.inputMethod.type = "fcitx5";
  services.xserver.xkb.layout = "jp";
  time.timeZone = "Asia/Tokyo";
}

